// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"context"
)

type Querier interface {
	CreateMovie(ctx context.Context, arg CreateMovieParams) (*Movie, error)
	DeleteMovie(ctx context.Context, id int32) error
	GetMovie(ctx context.Context, id int32) (*Movie, error)
	GetMovies(ctx context.Context) ([]*Movie, error)
	UpdateMovie(ctx context.Context, arg UpdateMovieParams) (*Movie, error)
}

var _ Querier = (*Queries)(nil)
